version: '3'

services:
  database:
    image: mysql:latest
    container_name: user-bonus-manager-database
    environment:
      - MYSQL_DATABASE=user-bonus-manager
      - MYSQL_PASSWORD=dev
      - MYSQL_ROOT_PASSWORD=dev
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - user-bonus-manager-net
    volumes:
      - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  php-fpm:
    container_name: user-bonus-manager-php
    build:
      context: .docker/php-fpm
    depends_on:
      - database
    volumes:
      - .:/opt
    networks:
      - user-bonus-manager-net

  nginx:
    image: nginx:alpine
    container_name: user-bonus-manager-nginx
    volumes:
      - .:/opt
      - .docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    tty: true
    networks:
      - user-bonus-manager-net

  memcached:
    container_name: user-bonus-manager-memcached
    image: memcached
    networks:
      - user-bonus-manager-net

networks:
  user-bonus-manager-net:
    driver: bridge
